export const ACTION = {
  ROUTER: 'ACTION_ROUTER',
  NICOACCOUNT: {
    CHANGE: 'ACTION_NICOACCOUNT_CHANGE',
    DELETE: 'ACTION_NICOACCOUNTDELETE'
  },
  QUEUE: {
    ADD: 'ACTION_QUEUE_ADD',
    MOVE: 'ACTION_QUEUE_MOVE',
    CLEAR: 'ACTION_QUEUE_CLEAR',
    DELETE: 'ACTION_QUEUE_DELETE',
    STATE: 'ACTION_QUEUE_STATE',
    SHUFFLE: 'ACTION_QUEUE_SHUFFLE'
  },
  PLAY: {
    STATE: 'ACTION_PLAY_STATE',
    END: 'ACTION_PLAY_END'
  },
  RANKING: {
    STATE: 'ACTION_RANKING_STATE'
  },
  SEARCH: {
    STATE: 'ACTION_SEARCH_STATE'
  },
  LOAD: {
    START: 'ACTION_LOAD_START',
    RANKING: 'ACTION_LOAD_RANKING',
    SEARCH: 'ACTION_LOAD_SEARCH'
  }
};

export const GET = {
  NICO: {
    LOGIN: 'GNL',

    API: {
      MYLIST: {
        PAGE: 'GNAMP',
        LIST: 'GNAML'
      },

      RANKING: 'GNAR',
      SEARCH: 'GET_NICO_API_SEARCH',
      SUGGEST: 'GET_NICO_API_SUGGEST',
      PLAY: 'GNAP',
      GETFLV: 'GET_NICO_API_GETFLV'
    }
  },

  IDB: {
    NICO_ACCOUNT: 'GINA'
  }
};
